require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # TestCompany. As you add validations to TestCompany, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestCompaniesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all test_companies as @test_companies" do
      test_company = TestCompany.create! valid_attributes
      get :index, {}, valid_session
      assigns(:test_companies).should eq([test_company])
    end
  end

  describe "GET show" do
    it "assigns the requested test_company as @test_company" do
      test_company = TestCompany.create! valid_attributes
      get :show, {:id => test_company.to_param}, valid_session
      assigns(:test_company).should eq(test_company)
    end
  end

  describe "GET new" do
    it "assigns a new test_company as @test_company" do
      get :new, {}, valid_session
      assigns(:test_company).should be_a_new(TestCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_company as @test_company" do
      test_company = TestCompany.create! valid_attributes
      get :edit, {:id => test_company.to_param}, valid_session
      assigns(:test_company).should eq(test_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestCompany" do
        expect {
          post :create, {:test_company => valid_attributes}, valid_session
        }.to change(TestCompany, :count).by(1)
      end

      it "assigns a newly created test_company as @test_company" do
        post :create, {:test_company => valid_attributes}, valid_session
        assigns(:test_company).should be_a(TestCompany)
        assigns(:test_company).should be_persisted
      end

      it "redirects to the created test_company" do
        post :create, {:test_company => valid_attributes}, valid_session
        response.should redirect_to(TestCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_company as @test_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestCompany.any_instance.stub(:save).and_return(false)
        post :create, {:test_company => { "name" => "invalid value" }}, valid_session
        assigns(:test_company).should be_a_new(TestCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestCompany.any_instance.stub(:save).and_return(false)
        post :create, {:test_company => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_company" do
        test_company = TestCompany.create! valid_attributes
        # Assuming there are no other test_companies in the database, this
        # specifies that the TestCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestCompany.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => test_company.to_param, :test_company => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested test_company as @test_company" do
        test_company = TestCompany.create! valid_attributes
        put :update, {:id => test_company.to_param, :test_company => valid_attributes}, valid_session
        assigns(:test_company).should eq(test_company)
      end

      it "redirects to the test_company" do
        test_company = TestCompany.create! valid_attributes
        put :update, {:id => test_company.to_param, :test_company => valid_attributes}, valid_session
        response.should redirect_to(test_company)
      end
    end

    describe "with invalid params" do
      it "assigns the test_company as @test_company" do
        test_company = TestCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_company.to_param, :test_company => { "name" => "invalid value" }}, valid_session
        assigns(:test_company).should eq(test_company)
      end

      it "re-renders the 'edit' template" do
        test_company = TestCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_company.to_param, :test_company => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_company" do
      test_company = TestCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => test_company.to_param}, valid_session
      }.to change(TestCompany, :count).by(-1)
    end

    it "redirects to the test_companies list" do
      test_company = TestCompany.create! valid_attributes
      delete :destroy, {:id => test_company.to_param}, valid_session
      response.should redirect_to(test_companies_url)
    end
  end

end
